### ISSUE TITLE
This is not actually Peer to Peer

### ISSUE THREAD

**Issue by tommedema** [Miserlou/DirtyShare#8]
You've been stating that this is an example of peer to peer in the browser. Most importantly, peer to peer implies that there is [no need for a central server](http://en.wikipedia.org/wiki/Peer-to-peer).

Conversely, this project is as dependent on a central server as dependency can go. So I've been wondering, why are you calling this peer to peer? Because data is not permanently stored on the server? That's completely irrelevant.

The way I see it, you only have limited options for peer to peer with node.js:
1. You'd have to write a client-side bridge for the actual P2P communication (as this cannot run in the browser)
2. You'd have to use Adobe Flash, with all its downfalls (RTMFP)

The first case has never been accomplished in node.js before, as far as I know. You'd need to have a great deal of knowledge about firewalls, networking, etc. And even so, many corporate firewalls won't allow any P2P traffic (RTMFP also suffers from this, a great many people cannot use it without going in to their router's settings).

The second case is almost certainly a no-go, due to [numerous issues](http://stackoverflow.com/a/6938011/45974)

**Comment by Miserlou** [comment]
This is a placeholder for when WebRTC-data becomes stable. Keep your eyes peeled. :)

**Comment by Miserlou** [comment]
Closing as a duplicate: https://github.com/Miserlou/DirtyShare/issues/4

**Comment by tommedema** [comment]
Nice, that'll be interesting. Thanks for the reply.

**Comment by Miserlou** [comment]
If you want to discuss what we're doing with that, please join the webp2p mailing list by emailing webp2p@librelist.com !
